## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Sierra Peng: Conceptualization, Data curation, Methodology, Writing - original draft

Dylan Nguyen: Project administration, Software, Visualization, Writing - original draft

Juan Bello:   Analysis, Software, Writing - review & editing

Ellen Kwon: Analysis, Background research, Visualization, Writing - original draft

Russel Wong: Conceptualization, Data curation, Analysis, Methodology

# Research Question

Is there a statistically significant correlation between ICE arrests and reported rates of rape, murder, robbery, and assault in Texas from 2019 to 2024?

## Background and Prior Work

Immigration and Customs Enforcement (ICE) is a federal agency acting under the Department of Homeland Security. The main responsibilities of ICE include enforcing immigration law, preventing terrorism, and stopping illegal movement of people and goods within the United States. 

The motivation for exploring our topic lies in the dramatic increase in funding that ICE has received with the One Big Beautiful Bill Act. Prior to the passage of the One Big Beautiful Bill Act, ICE received about 10 dollars billion in budget per year. After passing, funding increased to 85 billion dollars. With the marked uptick in funding, activity, and media coverage, ICE has become a hotly contested topic for the American public in recent months, especially with notable incidents involving Renee Good and Alex Pretti. We will attempt to gain a better understanding of the efficacy of ICE on reducing violent and property crime.<a name="cite_ref-1"></a>[<sup>1</sup>](#cite_note-1)

An article published in the The Journal of Law & Economics by Thomas J. Miles and Adam B. Cox examined the relationship between immigration enforcement and local US crime rates. The research specifically investigates the effect of the Secure Communities program. The Secure Communities program uses fingerprint-sharing between local law enforcement and federal immigration authorities to facilitate detention and removal of noncitizens. This is not a direct correlate to ICE, however, it may serve as a proxy to understand whether or not strict enforcement of immigration policy reduces crime. The conclusion of the study showed that the Secure Communities program led to hundreds of thousands of detentions, but did not reduce crime-rates as expected.<a name="cite_ref-2"></a>[<sup>2</sup>](#cite_note-2)

The article Immigration and Customs Enforcement Raids the Pillar of a Community: Student Achievement, Absenteeism, and Mobility Following a Large Worksite Enforcement Operation in North Texas looks at the effects that ICE had through various time extents. It serves as a point of interest as to why Texas was chosen for this project, as well as a way to question what sort of empirical and statistical impact ICE had.<a name="cite_ref-3"></a>[<sup>3</sup>](#cite_note-3)

Of all states affected by ICE, Texas stands out in the number and scale of people detained. According to data from the Transactional Records Access Clearinghouse (TRAC) Immigration, there are 18,684 people in detention, as of January 22, 2026, which makes Texas the state with the most ICE detainees followed by Louisiana, 8,207 people, and California, 6,422. Geographically, Texas shares the longest border between the U.S. and Mexico, stretching 382 miles, with more than 40 border security stations across 5 sectors. The sheer size of the border and affiliated border control stations are key in understanding the subsequent size of detainees in Texas, which should be considered when examining the correlation between violent crime and ICE arrests. While Texas holds the greatest number of detainees, it is critical to understand that detention location is not the same as arrest location. Texas maintains some of the largest ICE detention centers in the country, where those arrested by ICE both in and out of Texas may be placed into. Therefore it is more representative to examine arrests per capita, to measure the presence of ICE in Texas independent from other states.<a name="cite_ref-4"></a>[<sup>4,</sup>](#cite_note-4)<a name="cite_ref-5"></a>[<sup>5</sup>](#cite_note-5)

1. <a name="cite_note-1"></a> [^](#cite_ref-1) Chappell, Bill. “How ICE Grew to Be the Highest-Funded U.S. Law Enforcement Agency.” NPR, 21 Jan. 2026, www.npr.org/2026/01/21/nx-s1-5674887/ice-budget-funding-congress-trump. 
2. <a name="cite_note-2"></a> [^](#cite_ref-2) Miles, T. J., & Cox, A. B. (2014). Does Immigration Enforcement Reduce Crime? Evidence from Secure Communities. The Journal of Law and Economics, 57(4), 937–973. https://doi.org/10.1086/680935
3. <a name="cite_note-3"></a> [^](#cite_ref-3) J. Jacob Kirksey, and Carolyn Sattin-Bajaj. “Immigration and Customs Enforcement Raids the Pillar of a Community: Student Achievement, Absenteeism, and Mobility Following a Large Worksite Enforcement Operation in North Texas.” American Behavioral Scientist, 28 Nov. 2023, https://doi.org/10.1177/00027642231215992.
4. <a name="cite_note-4"></a> [^](#cite_ref-4)U.S. Customs and Border Protection. (2025, n.d.). Border Patrol sectors. U.S. Department of Homeland Security. https://www.cbp.gov/border-security/along-us-borders/border-patrol-sectors
5. <a name="cite_note-5"></a> [^](#cite_ref-5)Transactional Records Access Clearinghouse. (2026). Immigration Quick Facts. https://tracreports.org/immigration/quickfacts/

# Hypothesis

There will be no statistically significant relationship between the level of ICE arrests and rates of rape, murder, robbery, and assault in the state of Texas from 2019 to 2024. This hypothesis is based on the study on the Secure Communities program which did not reduce crime rates despite detaining hundreds of thousands of immigrants.

## Data

### Data overview

- Dataset #1
    - ICE Administrative Arrests
  - Link to the dataset: https://deportationdata.org/data/ice.html#historical-data-archive
  - Number of observations: 89,848 (Texas) 
  - Number of variables: 23
  - We will primarily be looking at the apprehension date and time made by an ICE officer. These two variables can tell us which area a crime was happening and the time of someones aprehension. We are tracking this throughout 2019-2024. 
  - Descriptions of any shortcomings this dataset has with respect to the project: The ICE dataset does not give precise arrest locations. It is under a broad area or a landmark that are used inconsistently in the report. Being able to localize arrest location would help us have finer tracking when it comes to crime rate in certain areas and trying to connect it with arrests happening in similar areas. 

    
- Dataset #2 
    - Texas Crime Reports 
  - Link to the dataset: https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/downloads
  - Number of observations: 966799 (2019) 
  - Number of variables: 8
  - We will be looking at the number of violent offense types of crimes happening from 2019-2024. Our main variable will be how many offense types, more specifically violent offenses, happened that year. Then track how many happen per year. 
  - Descriptions of any shortcomings this dataset has with respect to the project: Our main concern is that our data is aggregated at the state level and is not broken down by county or city. Because of this, we cannot examine regional variation within Texas. Any localized increases or decreases in violent crime may be hidden when looking at statewide totals. We are looking at pre and post Covid data. Irregularities wit policing patterns and crime might be common. 

Our goal is to examine trends over time and determine whether increases or decreases in ICE activity are linked to changes in violent crime levels.

In [ ]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
%pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1851831800585', 'filename':'ice_2018-2019.xlsx'},
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1851835191968', 'filename':'ice_2019-2020.xlsx'},
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1851833034596', 'filename':'ice_2020-2021.xlsx'},
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1851830686826', 'filename':'ice_2021-2022.xlsx'},
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1851836416108', 'filename':'ice_2022-2023.xlsx'},
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1851836311169', 'filename':'ice_2023-2024.xlsx'},
    { 'url': 'https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_2112094399060', 'filename':'ice_2024-2025.xlsx'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/ice_arrests')

In [ ]:
import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data
datafiles_crime = [
    { 'url': 'https://drive.google.com/uc?export=download&id=1vUrRUCDvJfnjMEV2k3jT-jD9QH6Ax1pz', 'filename':'texas_offenses_2019.csv'},
    { 'url': 'https://drive.google.com/uc?export=download&id=1-iGlPAfnkI9qUClc9H-a1ySWY-RYssAn', 'filename':'texas_offenses_2020.csv'},
    { 'url': 'https://drive.google.com/uc?export=download&id=1SPwSRvfHo7P_n1-VTypUk2qns6lJNUMB', 'filename':'texas_offenses_2021.csv'},
    { 'url': 'https://drive.google.com/uc?export=download&id=1YA20c8y5EfLCh3DdIoPPUpoNHUm6f9G8', 'filename':'texas_offenses_2022.csv'},
    { 'url': 'https://drive.google.com/uc?export=download&id=1q6mbYv2bzWPiUcX-12HkaA7m6D-FDkbT', 'filename':'texas_offenses_2023.csv'},
    { 'url': 'https://drive.google.com/uc?export=download&id=1nirFhfidk26ksytkGnWUBwSMWehyKK9P', 'filename':'texas_offenses_2024.csv'},
]

get_data.get_raw(datafiles_crime,destination_directory='data/00-raw/texas_crime_reports')

In [ ]:
import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data
datafiles_crime_monthly = [
    { 'url': 'https://drive.google.com/uc?export=download&id=12YQG8PDsgGaWl6T5xq94-rM0zdlzxXDy', 'filename':'texas_offenses_monthly.csv'}
]

get_data.get_raw(datafiles_crime_monthly,destination_directory='data/00-raw/texas_crime_reports_monthly')

### ICE Administrative Arrests 2018-2024

   1.  The ICE Administrative Arrest dataset primarily provides information about immigration-related apprehensions conducted by ICE. For this project, the key metric we use is Apprehension Date and Time. This variable records the specific date (and sometimes time) that an administrative arrest occurred. The unit of measurement is calendar time (year, month, day, and occasionally hour/minute). From this variable, we extract the year of each arrest in order to aggregate total ICE administrative arrests per year from 2019 through 2024
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"

In [48]:
import pandas as pd

In [49]:
def clean_ice_df(ice_df):
    # fix column names
    ice_df.columns = ice_df.iloc[3]

    # remove unecessary rows from beginning
    ice_df_drop = ice_df.iloc[4:].reset_index(drop=True)

    # keep only date and AOR columns
    ice_df_drop = ice_df_drop[['Apprehension AOR', 'Apprehension Date And Time']]

    # keep only Texas arrests
    texas_aor = ['Dallas Area of Responsibility', 
             'El Paso Area of Responsibility', 
             'Harlingen Area of Responsibility', 
             'Houston Area of Responsibility', 
             'San Antonio Area of Responsibility']
    ice_df_texas = ice_df_drop[ice_df_drop['Apprehension AOR'].isin(texas_aor)]

    #filter for years 2019-2024
    ice_df_texas['Apprehension Date And Time'] = pd.to_datetime(
    ice_df_texas['Apprehension Date And Time'], errors='coerce')
    ice_df_2019_2024 = ice_df_texas[
    ice_df_texas['Apprehension Date And Time'].dt.year.between(2019, 2024)]

    #remove any nan rows
    ice_df_clean = ice_df_2019_2024.dropna()
    
    return ice_df_clean

In [50]:
# years of each data file
years = [[2018, 2019],
 [2019, 2020],
 [2020, 2021],
 [2021, 2022],
 [2022, 2023],
 [2023, 2024],
 [2024, 2025]]

clean_dfs = []  # list to store cleaned dataframes

for yr in years:
    year_start, year_end = yr

    # load data and clean it 
    ice_df = pd.read_excel(f'data/00-raw/ice_arrests/ice_{year_start}-{year_end}.xlsx')
    clean_ice = clean_ice_df(ice_df)

    # append to the list
    clean_dfs.append(clean_ice)

# concatenate all cleaned dataframes into one
final_clean_ice = pd.concat(clean_dfs, ignore_index=True)

KeyboardInterrupt:

In [ ]:
# save final clean data 
final_clean_ice.to_csv('data/02-processed/ice_arrests_clean.csv', index=False)

In [53]:
# Reload the saved clean ICE data
final_clean_ice = pd.read_csv('data/02-processed/ice_arrests_clean.csv')

display(final_clean_ice.head())
print("Shape:", final_clean_ice.shape)
print("\nData Types:\n", final_clean_ice.dtypes)
print("\nNull Counts:\n", final_clean_ice.isnull().sum())
print("\nNull Proportions:\n", final_clean_ice.isnull().mean().round(4))
print("\nArrests by Year:\n", pd.to_datetime(final_clean_ice['Apprehension Date And Time']).dt.year.value_counts().sort_index())
print("\nArrests by Texas AOR:\n", final_clean_ice['Apprehension AOR'].value_counts())

missing_apprehensions = final_clean_ice['Apprehension Date And Time'].isna().sum()
print("\nRows missing apprehension timestamp:", missing_apprehensions)

parsed_dates = pd.to_datetime(
    final_clean_ice['Apprehension Date And Time'],
    errors='coerce'
)

invalid_dates = parsed_dates.isna().sum()
print("Invalid apprehension timestamps:", invalid_dates)

print("Total rows:", len(final_clean_ice))
print("Total valid apprehension timestamps:", parsed_dates.notna().sum())

if 'Arrest ID' in final_clean_ice.columns:
    print("Duplicate arrests:", final_clean_ice['Arrest ID'].duplicated().sum())

                Apprehension AOR Apprehension Date And Time
0  Dallas Area of Responsibility        2019-03-07 08:22:00
1  Dallas Area of Responsibility        2019-01-07 10:32:00
2  Dallas Area of Responsibility        2019-01-07 10:22:00
3  Dallas Area of Responsibility        2019-05-02 09:38:00
4  Dallas Area of Responsibility        2019-05-19 09:43:00

Shape: (208235, 2)

Data Types:
 Apprehension AOR              object
Apprehension Date And Time    object
dtype: object

Null Counts:
 Apprehension AOR              0
Apprehension Date And Time    0
dtype: int64

Null Proportions:
 Apprehension AOR              0.0
Apprehension Date And Time    0.0
dtype: float64

Arrests by Year:
 Apprehension Date And Time
2019    42039
2020    30780
2021    23715
2022    40479
2023    42847
2024    28375
Name: count, dtype: int64

Arrests by Texas AOR:
 Apprehension AOR
Dallas Area of Responsibility         75762
Houston Area of Responsibility        56995
San Antonio Area of Responsibility    43596
Harlingen Area of Responsibility      19552
El Paso Area of Responsibility        12330
Name: count, dtype: int64

Rows missing apprehension timestamp: 0
Invalid apprehension timestamps: 0
Total rows: 208235
Total valid apprehension timestamps: 208235

## Texas Crime Report Offences

The Texas Crime Reports dataset provides statewide arrest data collected through the FBI’s Uniform Crime Reporting (UCR) system. For this project, the primary metric we are using is the number of violent offense arrests per year from 2019 through 2024. Violent offenses typically include crimes such as homicide, aggravated assault, robbery, and sexual assault. The unit of measurement is a simple count of arrests. For example, if there were 50,000 violent offense arrests in 2019 and 45,000 in 2020, that would represent a decrease of 5,000 arrests year over year. By aggregating violent offense counts annually, we can observe whether violent crime trends increased, decreased, or remained relatively stable over time. These yearly totals allow us to compare patterns before, during, and after the COVID-19 period.

If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person. Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"

In [ ]:
# Loading dataframes for every year
texas_offenses_2019 = pd.read_csv('data/00-raw/texas_crime_reports/texas_offenses_2019.csv')
texas_offenses_2020 = pd.read_csv('data/00-raw/texas_crime_reports/texas_offenses_2020.csv')
texas_offenses_2021 = pd.read_csv('data/00-raw/texas_crime_reports/texas_offenses_2021.csv')
texas_offenses_2022 = pd.read_csv('data/00-raw/texas_crime_reports/texas_offenses_2022.csv')
texas_offenses_2023 = pd.read_csv('data/00-raw/texas_crime_reports/texas_offenses_2023.csv')
texas_offenses_2024 = pd.read_csv('data/00-raw/texas_crime_reports/texas_offenses_2024.csv')

In [ ]:
# -----------------------------
# SETUP
# -----------------------------

list_of_dfs = [
    texas_offenses_2019,
    texas_offenses_2020,
    texas_offenses_2021,
    texas_offenses_2022,
    texas_offenses_2023,
    texas_offenses_2024
]

# Standard UCR offense codes
offense_codes_standard = {
    '11A': 'Rape',
    '09A': 'Murder and Nonnegligent Manslaughter',
    '120': 'Robbery',
    '13A': 'Aggravated Assault'
}

# Alternate coding system
offense_codes_alt = {
    '36': 'Rape',
    '32': 'Murder and Nonnegligent Manslaughter',
    '40': 'Robbery',
    '27': 'Aggravated Assault'
}

# DataFrames that use alternate codes
alt_code_indices = [0, 1]

processed_dfs = []

# -----------------------------
# PROCESS DATA
# -----------------------------

for i, df in enumerate(list_of_dfs):

    # Normalize column names
    df = df.copy()
    df.columns = df.columns.str.lower()

    # Standardize offense column name
    if 'offense_type_id' in df.columns:
        df = df.rename(columns={'offense_type_id': 'offense_code'})

    # Select only needed columns
    df = df.loc[:, ['data_year', 'offense_code']]

    # Normalize offense_code values
    df['offense_code'] = (
        df['offense_code']
        .astype(str)
        .str.strip()
        .str.upper()
    )

    # Apply correct mapping
    if i in alt_code_indices:
        df['offense_code'] = df['offense_code'].map(offense_codes_alt)
    else:
        df['offense_code'] = df['offense_code'].map(offense_codes_standard)

    # Drop rows not in our crimes of interest
    df = df.dropna(subset=['offense_code'])

    processed_dfs.append(df)

# -----------------------------
# COMBINE ALL DATA
# -----------------------------

texas_offenses_all = pd.concat(processed_dfs, ignore_index=True)

# -----------------------------
# SAVE TO 02-PROCESSED
# -----------------------------

output_dir = "data/02-processed"
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(output_dir, "texas_offenses_clean.csv")
texas_offenses_all.to_csv(output_path, index=False)

In [18]:
# Reload the saved clean crime data
texas_offenses_all = pd.read_csv('data/02-processed/texas_offenses_clean.csv')

display(texas_offenses_all.head())

print("Shape:", texas_offenses_all.shape)
print("\nData Types:\n", texas_offenses_all.dtypes)
print("\nNull Counts:\n", texas_offenses_all.isnull().sum())
print("\nNull Proportions:\n", texas_offenses_all.isnull().mean().round(4))
print("\nOffenses by Year:\n", texas_offenses_all['data_year'].value_counts().sort_index())
print("\nOffense Type Breakdown:\n", texas_offenses_all['offense_code'].value_counts())
print("\nOffense Type by Year:")
print(pd.crosstab(texas_offenses_all['data_year'], texas_offenses_all['offense_code']))

print(f"\nNumber of unique rows in offense_id: {texas_offenses_all['offense_id'].nunique()} | This matches the number of rows in the dataset, therefore, each row is an arrest.")

   data_year        offense_code  offense_id
0       2019  Aggravated Assault   138373905
1       2019  Aggravated Assault   138384764
2       2019  Aggravated Assault   138375422
3       2019             Robbery   138386805
4       2019  Aggravated Assault   138386979

Shape: (583834, 3)

Data Types:
 data_year        int64
offense_code    object
offense_id       int64
dtype: object

Null Counts:
 data_year       0
offense_code    0
offense_id      0
dtype: int64

Null Proportions:
 data_year       0.0
offense_code    0.0
offense_id      0.0
dtype: float64

Offenses by Year:
 data_year
2019     67504
2020     91819
2021    109716
2022    107830
2023    104051
2024    102914
Name: count, dtype: int64

Offense Type Breakdown:
 offense_code
Aggravated Assault                      388490
Robbery                                 128825
Rape                                     57230
Murder and Nonnegligent Manslaughter      9289
Name: count, dtype: int64

Offense Type by Year:
offense_code  Aggravated Assault  Murder and Nonnegligent Manslaughter   Rape  \
data_year
2019                       39900                                   838   5916
2020                       59301                                  1499   7690
2021                       74598                                  1908  10771
2022                       74037                                  1814  10760
2023                       70382                                  1718  10889
2024                       70272                                  1512  11204

offense_code  Robbery
data_year
2019            20850
2020            23329
2021            22439
2022            21219
2023            21062
2024            19926

Number of unique rows in offense_id: 583834 | This matches the number of rows in the dataset, therefore, each row is an arrest.

## Texas Crime Reports - Monthly

This dataset is from the same source as the previous dataset. Our group has decided to add this dataset to get finer-grain detail on the rise and fall of crime rates on a monthly basis, rather than yearly. The variables of this dataset are the type of crime, the month the crime was committed in, and number of attempted, completed, and total crimes for the month. This data will be used to track crime rates per month, and can be broken down further to analyze the type of crime committed per month.

In [47]:
import pandas as pd
import os

# Load dataframe from 00-raw
monthly_crime_df = pd.read_csv('data/00-raw/texas_crime_reports_monthly/texas_offenses_monthly.csv')

# Forward-fill offense names
monthly_crime_df['Offense'] = monthly_crime_df['Offense'].ffill()

# Keep only required offense codes
target_codes = ['11A', '09A', '120', '13A']
monthly_crime_df = monthly_crime_df[
    monthly_crime_df['Offense'].str.contains('|'.join(target_codes), na=False)
].copy()

# Map to clean offense names
offense_labels = {
    '11A': 'Rape',
    '09A': 'Murder and Nonnegligent Manslaughter',
    '120': 'Robbery',
    '13A': 'Aggravated Assault'
}

monthly_crime_df['OffenseCode'] = monthly_crime_df['Offense'].str.extract(r'(11A|09A|120|13A)')
monthly_crime_df['Offense'] = monthly_crime_df['OffenseCode'].map(offense_labels)

# Clean month column
monthly_crime_df['Month'] = pd.to_datetime(
    monthly_crime_df['Month'],
    format='%b - %Y'
)

# Remove commas from numeric columns
cols = ['Attempted', 'Completed', 'Total']
for col in cols:
    monthly_crime_df[col] = (
        monthly_crime_df[col]
        .astype(str)
        .str.replace(',', '', regex=False)
    )

# Convert numeric columns
monthly_crime_df[cols] = monthly_crime_df[cols].apply(
    pd.to_numeric,
    errors='coerce'
)

# Convert to tidy format
tidy_crime_df = monthly_crime_df.melt(
    id_vars=['Month', 'Offense'],
    value_vars=['Attempted', 'Completed'],
    var_name='Outcome',
    value_name='Count'
).dropna(subset=['Count'])

# Sort
tidy_crime_df = tidy_crime_df.sort_values(['Offense', 'Month'])

# Save cleaned file
output_dir = "data/02-processed"
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(output_dir, "texas_offenses_monthly_clean.csv")
tidy_crime_df.to_csv(output_path, index=False)

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
# plot distribution of ICE arrests over time
import pandas as pd
import matplotlib.pyplot as plt

# load data
ice_df = pd.read_csv('data/02-processed/ice_arrests_clean.csv')

# find counts of arrests per month
ice_df['datetime'] = pd.to_datetime(ice_df['Apprehension Date And Time'])
monthly = ice_df.set_index('datetime').resample('M').size()

# plot figure
plt.figure()
plt.plot(monthly.index, monthly.values)
plt.xlabel('Date')
plt.ylabel('Number of ICE Arrests')
plt.title('Monthly ICE Arrests Over Time')
plt.xticks(rotation=45)
plt.show()

An initial look at the data shows that the number of ICE arrests greatly vary month to month from 2019-2025. This volatility is due to a number of funding cycles and policy shifts. For example, ICE arrests are limited when detention centers are full. When the budget increases ([One Big Beautiful Bill Act](https://www.npr.org/2026/01/21/nx-s1-5674887/ice-budget-funding-congress-trump)) the capacity to detain more people increases, leading to a spike in the graph.

In [ ]:
def plot_time_series(crime, crime_type):
    # function for plotting distribution of crime over time

    # find counts of crime per year
    yearly_counts = crime.groupby('data_year').size()

    # plot figure
    plt.figure()
    plt.plot(yearly_counts.index, yearly_counts.values)
    plt.xlabel('Year')
    if crime_type == 'Crime (all)':
        plt.ylabel('Number of Crimes (all)')
        plt.title(f'{crime_type} Per Year')
    elif crime_type == 'Robbery':
        plt.ylabel('Number of Robberies')
        plt.title('Robberies Per Year')
    else:
        plt.ylabel(f'Number of {crime_type}s')
        plt.title(f'{crime_type}s Per Year')
    plt.show()

In [ ]:
# load data
crime_df = pd.read_csv('data/02-processed/texas_offenses_clean.csv')

# plot time series of crime overall
plot_time_series(crime_df, 'Crime (all)')

# plot time series for each type of crime
crime_categories = ['Rape', 'Murder and Nonnegligent Manslaughter', 'Robbery', 'Aggravated Assault']

for crime_type in crime_categories:
    crime_df_new = crime_df[crime_df['offense_code'] == crime_type]
    plot_time_series(crime_df_new, crime_type)

It is evident that the number of crimes increased between the years 2019 and 2021. This aligns with the COVID-19 pandemic, which caused social disruption and economic stress in Texas. One potential factor to consider is the increase of firearm presence in Texas. According to ammo.com, over 5 million firearms were purchased between 2020 and 2023. Is the decrease of the amount of crime caused by an increase of ICE arrests?

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
def plot_correlation(crime, crime_type):
    # function for plotting correlation between ICE arrests and crime

    # find counts of ICE arrests and crime by year
    ice_yearly = ice_df.set_index('datetime').resample('Y').size()
    ice_yearly.index = ice_yearly.index.year
    crime_yearly = crime.groupby('data_year').size()

    # combine ICE arrests and crime into one dataframe
    combined = pd.DataFrame({
        'ice_arrests': ice_yearly,
        'crime_count': crime_yearly
    })

    # plotting
    sns.regplot(x='ice_arrests', y='crime_count', data=combined)

    plt.title(f'Correlation Between ICE Arrests and {crime_type}')
    plt.xlabel('ICE Arrests')
    plt.ylabel(f'{crime_type} Count')
    plt.show()

    # print out correlation coefficient
    corr_value = combined['ice_arrests'].corr(combined['crime_count'])
    print(f'Correlation coefficient is {corr_value:.3f}')

In [ ]:
import seaborn as sns

# plot correlation between ICE arrests and crime overall
plot_correlation(crime_df, 'All Crime')

# plot correlation between ICE arrests and each type of crime
crime_categories = ['Rape', 'Murder and Nonnegligent Manslaughter', 'Robbery', 'Aggravated Assault']

for crime_type in crime_categories:
    crime_df_new = crime_df[crime_df['offense_code'] == crime_type]
    plot_correlation(crime_df_new, crime_type)

## Ethics

## Ethics 

Instructions: Keep the contents of this cell. For each item on the checklist
-  put an X there if you've considered the item
-  IF THE ITEM IS RELEVANT place a short paragraph after the checklist item discussing the issue.
  
Items on this checklist are meant to provoke discussion among good-faith actors who take their ethical responsibilities seriously. Your teams will document these discussions and decisions for posterity using this section.  You don't have to solve these problems, you just have to acknowledge any potential harm no matter how unlikely.

Here is a [list of real world examples](https://deon.drivendata.org/examples/) for each item in the checklist that can refer to.

[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/)

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?
 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

There could be some sources of bias in our data, for example since the ICE arrest records come from ICE themselves, we do not know if they choose to leave certain arrests unrecorded. The same type of bias also applies to the data of crime rate, since some crimes may go unrecorded. Also, there could be bias in the way that the data was recorded across different areas, for instance some places could be more strict in what they record than others. 

 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

The data we are using does not use personally identifiable information.  The data sources has encrypted any identifying documents. We still have data about demographics and location, but people’s personal information is safe. 

 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

The methods used in this project should be able to be applied on data collected in the future so long as the formatting of data is similar.


### B. Data Storage
 - [X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

Since our data was obtained from reputable open sources, the danger of exposing personal information was extremely minimal. While encryption at rest and in transit is not applicable, our data will be stored on the private team project repository only accessible by invited members on Github. Any changes to our data will be recorded by version control, to minimize accidental deletion or modifications.  

 - [X] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [X] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

Data will only be accessed during the progression of the project and later deleted from our local systems upon completion. The data will exist in the Github repository with no plan to delete it for future academic purposes. 


### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

We plan on making sure that we do not reinforce harmful stereotypes by discussing amongst each other as well as reaching out to those in affected communities

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

We are aware of the possibilities of misreporting statistics and other variables and will try to account for this error

 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?

We will only present what the data shows and not draw any unnecessary conclusions.

 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
    
This data doesn't use personally identifiable information. In case we come across this, we will not display any unnecessary data that may break privacy. 

 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

We will document our process of analysis with explanations of our findings. The documentation of our analysis will include every step we took to analyze the data so that it will be reproducible in the future.


### D. Modeling
 - [ ] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?
 - [ ] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
 - [ ] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 - [ ] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [ ] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

### E. Deployment
 - [ ] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [ ] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [ ] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

## Team Expectations

* *Each group member should check in regularly and respond within a reasonable timeframe to ensure tasks are coordinated and questions are addressed quickly.*
* *Every team member contributes meaningfully to all project phases and is accountable for completing assigned tasks on time. 2*
* *All work should be committed to the team’s GitHub repository with clear commit messages, frequent commits, and proper branching (e.g., each feature on its own branch) to ensure version control and transparency among teammates. 3*
* *Team members should treat each other with respect, be open to constructive feedback, and resolve differences through discussion and compromise to maintain a productive team environment.*

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/20  |  1 PM | Read & Think about COGS 108 expectations; brainstorm topics/questions  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 1/26  |  10 AM |  Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 2/3  |  5 PM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 2/14  | 6 PM  | Import & Wrangle Data (Juan); EDA (Dylan) | Review/Edit wrangling/EDA; Discuss Analysis Plan   |
| 2/23  | 12 PM  | Finalize wrangling/EDA; Begin Analysis (Russell; Sierra) | Discuss/edit Analysis; Complete project check-in |
| 3/13  | 12 PM  | Complete analysis; Draft results/conclusion/discussion (Ellen)| Discuss/edit full project |
| 3/20  | Before 11:59 PM  | NA | Turn in Final Project & Group Project Surveys |